server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_info?useUnicode=true&characterEncoding=utf-8&serverTimezone = GMT%2B8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    suffix: .html
    cache: false
    template-loader-path: classpath:/templates/
    charset: utf-8
    enabled: true
  devtools:
    restart:
      enabled: true

# mybatis扫描
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.nantian.employeeinfo.domain
